import type { LexiconConcept } from "./lexicon-types.js";

/** Bilingual concept groups consumed by security-rules.ts. */
export const SECURITY_LEXICON = {
  authTopic: {
    en: [
      "authentication",
      "authorization",
      "endpoint",
      "auth strategy",
      "caller identity",
    ],
    fr: [
      "authentification",
      "autorisation",
      "point de terminaison",
      "stratégie d'authentification",
      "identité de l'appelant",
    ],
  },
  authNSignals: {
    en: [
      "authentication",
      "authenticate",
      "login",
      "sign in",
      "jwt",
      "oauth",
      "api key",
      "bearer token",
      "session",
      "identity",
      "credential",
      "mfa",
      "multi-factor",
      "sso",
    ],
    fr: [
      "authentification",
      "authentifier",
      "connexion",
      "se connecter",
      "jeton porteur",
      "session",
      "identité",
      "identifiants",
      "authentification multifacteur",
      "authentification à double facteur",
      "authentification unique",
    ],
  },
  authZSignals: {
    en: [
      "authorization",
      "authorize",
      "permission",
      "role",
      "rbac",
      "abac",
      "access control",
      "privilege",
      "scope",
      "claim",
      "policy",
      "grant",
    ],
    fr: [
      "autorisation",
      "autoriser",
      "permission",
      "rôle",
      "contrôle d'accès",
      "privilège",
      "périmètre d'accès",
      "revendication",
      "politique d'accès",
      "octroi",
    ],
  },
  inputValidationTopic: {
    en: ["input validation", "external input", "user input", "request"],
    fr: [
      "validation des entrées",
      "entrée externe",
      "entrée utilisateur",
      "requête",
    ],
  },
  inputValidationSignals: {
    en: [
      "input validation",
      "validate input",
      "sanitize",
      "sanitization",
      "whitelist",
      "allowlist",
      "blocklist",
      "reject invalid",
      "schema validation",
      "request validation",
      "payload validation",
      "type check",
      "bounds check",
      "length check",
      "format validation",
      "validate request",
      "input filter",
      "data validation",
    ],
    fr: [
      "validation des entrées",
      "valider les entrées",
      "assainir",
      "assainissement",
      "liste blanche",
      "liste noire",
      "rejeter les entrées invalides",
      "validation de schéma",
      "validation de la requête",
      "validation du payload",
      "vérification de type",
      "vérification des limites",
      "vérification de la longueur",
      "validation du format",
      "filtre d'entrée",
      "validation des données",
    ],
  },
  injectionTopic: {
    en: ["injection", "output encoding", "xss", "sql"],
    fr: ["injection", "encodage de sortie", "script intersite", "sql"],
  },
  injectionSignals: {
    en: [
      "injection prevention",
      "sql injection",
      "xss",
      "cross-site scripting",
      "command injection",
      "output encoding",
      "escape",
      "parameterized quer",
      "prepared statement",
      "orm",
      "html encoding",
      "content security policy",
      "csp",
      "sanitize output",
      "template escaping",
      "injection attack",
    ],
    fr: [
      "prévention des injections",
      "injection sql",
      "script intersite",
      "injection de commande",
      "encodage de sortie",
      "échappement",
      "requête paramétrée",
      "requête préparée",
      "encodage html",
      "politique de sécurité du contenu",
      "assainir la sortie",
      "échappement de gabarit",
      "attaque par injection",
    ],
  },
  safeErrorTopic: {
    en: ["client-facing error", "error response", "error message", "error"],
    fr: [
      "erreur destinée au client",
      "réponse d'erreur",
      "message d'erreur",
      "erreur",
    ],
  },
  safeErrorSignals: {
    en: [
      "no stack trace",
      "hide internal",
      "generic error",
      "error message sanitiz",
      "no implementation detail",
      "user-facing error",
      "error boundary",
      "safe error",
      "don't leak",
      "do not expose",
      "error abstraction",
      "error mapping",
      "client-safe",
      "production error",
    ],
    fr: [
      "pas de trace de pile",
      "masquer les détails internes",
      "erreur générique",
      "assainissement du message d'erreur",
      "aucun détail d'implémentation",
      "erreur destinée à l'utilisateur",
      "erreur sécurisée",
      "ne pas divulguer",
      "ne pas exposer",
      "abstraction des erreurs",
      "erreur adaptée au client",
      "erreur de production",
    ],
  },
  dangerousSecretPhrases: {
    en: [
      "hardcode the password",
      "hardcode the key",
      "embed the secret",
      "paste your api key",
      "put your token directly",
    ],
    fr: [
      "coder en dur le mot de passe",
      "coder en dur la clé",
      "intégrer le secret directement",
      "coller votre clé api directement",
      "mettre votre jeton directement",
    ],
  },
  cryptoTopic: {
    en: ["encrypt", "encryption", "cryptograph", "hash", "key management"],
    fr: ["chiffrement", "cryptographie", "hachage", "gestion des clés"],
  },
  cryptoSignals: {
    en: [
      "encrypt",
      "encryption",
      "aes",
      "rsa",
      "tls",
      "hash",
      "bcrypt",
      "argon2",
      "scrypt",
      "pbkdf2",
      "hmac",
      "sha-256",
      "sha-384",
      "sha-512",
      "key management",
      "key rotation",
      "certificate",
    ],
    fr: [
      "chiffrement",
      "chiffré",
      "hachage",
      "gestion des clés",
      "rotation des clés",
      "certificat",
    ],
  },
  rateLimitTopic: {
    en: [
      "rate limit",
      "rate limiting",
      "throttl",
      "endpoint",
      "abuse prevention",
    ],
    fr: [
      "limitation de débit",
      "limitation de taux",
      "point de terminaison",
      "prévention des abus",
    ],
  },
  rateLimitSignals: {
    en: [
      "rate limit",
      "rate-limit",
      "throttl",
      "request limit",
      "quota",
      "burst limit",
      "sliding window",
      "token bucket",
      "leaky bucket",
      "ddos",
      "abuse prevention",
      "requests per",
      "calls per",
    ],
    fr: ["limitation de débit", "limitation de taux", "limite de requêtes"],
  },
  secureCommTopic: {
    en: [
      "tls",
      "https",
      "network i/o",
      "network",
      "secure communication",
      "transport",
      "encrypted channel",
    ],
    fr: [
      "réseau",
      "communication sécurisée",
      "canal chiffré",
      "trafic réseau",
    ],
  },
  secureCommSignals: {
    en: [
      "tls",
      "https",
      "ssl",
      "transport layer security",
      "encrypt in transit",
      "encryption in transit",
      "certificate",
      "cert pinning",
      "certificate pinning",
      "mutual tls",
      "mtls",
      "secure channel",
      "encrypted connection",
    ],
    fr: [
      "chiffrement en transit",
      "canal sécurisé",
      "connexion chiffrée",
      "certificat",
    ],
  },
} as const satisfies Record<string, LexiconConcept>;
