import type { LexiconConcept } from "./lexicon-types.js";

/** Bilingual concept groups consumed by senior-quality-rules.ts. */
export const QUALITY_LEXICON = {
  namedConstantSignals: {
    en: [
      "named constant",
      "named variable",
      "const ",
      "static let",
      "static final",
      "companion object",
      "no magic number",
      "extract constant",
      "configuration value",
    ],
    fr: [
      "constante nommée",
      "constantes nommées",
      "variable nommée",
      "aucun nombre magique",
      "extraire en constante",
      "valeur de configuration",
    ],
  },
  namingConventionSignals: {
    en: [
      "naming convention",
      "naming standard",
      "naming rule",
      "camelcase",
      "camel case",
      "snake_case",
      "snake case",
      "pascalcase",
      "pascal case",
      "kebab-case",
      "descriptive name",
      "self-documenting",
      "meaningful name",
      "no abbreviation",
      "full word",
      "consistent naming",
    ],
    fr: [
      "convention de nommage",
      "conventions de nommage",
      "règle de nommage",
      "nom descriptif",
      "nom explicite",
      "nommage cohérent",
      "pas d'abréviation",
    ],
  },
  defensiveCodingSignals: {
    en: [
      "guard",
      "precondition",
      "require",
      "assert",
      "null safe",
      "null check",
      "nil check",
      "optional",
      "non-null",
      "nonnull",
      "notnull",
      "bounds check",
      "range check",
      "defensive",
      "fail fast",
      "early return",
      "validation",
      "contract",
      "invariant",
    ],
    fr: [
      "garde",
      "précondition",
      "vérification de nullité",
      "sécurité vis-à-vis des valeurs nulles",
      "vérification des limites",
      "vérification de plage",
      "défensif",
      "échec rapide",
      "retour anticipé",
      "validation",
      "contrat",
      "invariant",
    ],
  },
  apiContractTopic: {
    en: ["api contract", "endpoint", "api", "public interface"],
    fr: ["contrat d'api", "point de terminaison", "api", "interface publique"],
  },
  apiContractDocumentationSignals: {
    en: [
      "request schema",
      "response schema",
      "api contract",
      "openapi",
      "swagger",
      "api spec",
      "endpoint spec",
      "request body",
      "response body",
      "status code",
      "content-type",
      "accept header",
      "api documentation",
      "typed request",
      "typed response",
    ],
    fr: [
      "schéma de requête",
      "schéma de réponse",
      "contrat d'api",
      "spécification d'api",
      "spécification de point de terminaison",
      "corps de la requête",
      "corps de la réponse",
      "code de statut",
      "documentation de l'api",
      "requête typée",
      "réponse typée",
    ],
  },
  deprecationTopic: {
    en: ["deprecation", "api version", "breaking change", "public api"],
    fr: [
      "dépréciation",
      "version de l'api",
      "changement incompatible",
      "api publique",
    ],
  },
  deprecationStrategySignals: {
    en: [
      "deprecat",
      "sunset",
      "breaking change",
      "migration path",
      "backward compat",
      "backwards compat",
      "version",
      "api version",
      "v1",
      "v2",
      "changelog",
      "upgrade guide",
      "migration guide",
    ],
    fr: [
      "obsolèt",
      "dépréciat",
      "fin de vie",
      "changement incompatible",
      "chemin de migration",
      "rétrocompatibilité",
      "version",
      "version de l'api",
      "journal des modifications",
      "guide de mise à niveau",
      "guide de migration",
    ],
  },
} as const satisfies Record<string, LexiconConcept>;
