import type { LexiconConcept } from "./lexicon-types.js";

/** Bilingual concept groups consumed by observability-rules.ts. */
export const OBSERVABILITY_LEXICON = {
  structuredLoggingTopic: {
    en: ["logging", "log format", "log level"],
    fr: ["journalisation", "format de journal", "niveau de journalisation"],
  },
  structuredLoggingFormatSignals: {
    en: [
      "structured log",
      "json log",
      "log format",
      "log schema",
      "log standard",
      "log framework",
    ],
    fr: [
      "journalisation structurée",
      "journal json",
      "format de journal",
      "schéma de journal",
      "norme de journalisation",
      "cadre de journalisation",
    ],
  },
  structuredLoggingLevelSignals: {
    en: [
      "log level",
      "debug",
      "info",
      "warn",
      "error",
      "trace",
      "fatal",
      "severity",
      "verbosity",
    ],
    fr: [
      "niveau de journalisation",
      "avertissement",
      "erreur",
      "gravité",
      "verbosité",
      "critique",
    ],
  },
  distributedTracingTopic: {
    en: [
      "distributed tracing",
      "tracing",
      "correlation id",
      "single-process",
      "single process",
      "cross-service",
      "second hop",
    ],
    fr: [
      "traçage distribué",
      "traçage",
      "identifiant de corrélation",
      "processus unique",
      "monoprocessus",
    ],
  },
  distributedTracingSignals: {
    en: [
      "correlation id",
      "trace id",
      "request id",
      "distributed trac",
      "opentelemetry",
      "jaeger",
      "zipkin",
      "trace context",
      "span",
      "trace propagat",
      "x-request-id",
      "x-correlation-id",
      "end-to-end trac",
      "cross-service trac",
    ],
    fr: [
      "identifiant de corrélation",
      "traçage distribué",
      "propagation de trace",
    ],
  },
  piiObservabilityTopic: {
    en: [
      "pii",
      "observability",
      "personal data",
      "logs",
      "metrics",
      "traces",
      "dashboards",
    ],
    fr: [
      "données personnelles",
      "observabilité",
      "journaux",
      "métriques",
      "traces",
      "tableaux de bord",
    ],
  },
  piiObservabilitySignals: {
    en: [
      "no pii in log",
      "no pii in metric",
      "no pii in trace",
      "mask sensitive",
      "redact",
      "scrub",
      "sanitize log",
      "filter pii",
      "exclude sensitive",
      "log safe",
      "safe to log",
      "no personal data in",
    ],
    fr: [
      "aucune donnée personnelle dans les journaux",
      "aucune donnée personnelle dans les métriques",
      "aucune donnée personnelle dans les traces",
      "masquer les données sensibles",
      "caviarder",
      "nettoyer",
      "assainir les journaux",
      "filtrer les données personnelles",
      "exclure les données sensibles",
      "sûr à journaliser",
      "aucune donnée personnelle dans",
    ],
  },
  piiObservabilityBroaderTopicSignals: {
    en: ["pii", "sensitive", "personal data"],
    fr: ["données personnelles", "sensible", "sensibles"],
  },
  piiObservabilitySurfaceSignals: {
    en: ["log", "metric", "trace", "monitor"],
    fr: ["journal", "métrique", "trace", "surveillance", "supervision"],
  },
  piiObservabilityActionSignals: {
    en: ["never", "must not", "exclude", "prevent", "mask", "redact"],
    fr: ["jamais", "ne doit pas", "exclure", "empêcher", "masquer", "caviarder"],
  },
  alertingTopic: {
    en: ["alerting", "alert", "on-call", "incident response"],
    fr: ["alerte", "alerting", "astreinte", "réponse aux incidents"],
  },
  alertingSignals: {
    en: [
      "alert",
      "alerting",
      "threshold",
      "alarm",
      "escalat",
      "on-call",
      "pagerduty",
      "opsgenie",
      "notification",
      "sla breach",
      "slo",
      "warning threshold",
      "critical threshold",
      "runbook",
      "incident response",
    ],
    fr: [
      "alerte",
      "alerting",
      "seuil",
      "escalade",
      "astreinte",
      "notification",
      "violation de sla",
      "seuil d'avertissement",
      "seuil critique",
      "réponse aux incidents",
    ],
  },
} as const satisfies Record<string, LexiconConcept>;
