import type { LexiconConcept } from "./lexicon-types.js";

/** Bilingual concept groups consumed by data-protection-rules.ts. */
export const DATA_PROTECTION_LEXICON = {
  dataClassificationTopic: {
    en: [
      "data classification",
      "sensitivity",
      "pii",
      "personal data",
      "sensitive data",
    ],
    fr: [
      "classification des données",
      "sensibilité",
      "données personnelles",
      "données sensibles",
    ],
  },
  dataClassificationSignals: {
    en: [
      "data classification",
      "classify",
      "classification level",
      "public data",
      "internal data",
      "confidential",
      "restricted",
      "sensitivity level",
      "sensitivity class",
      "data tier",
      "data category",
      "personal data",
      "non-personal",
      "pii",
      "phi",
      "pci",
      "sensitive data",
    ],
    fr: [
      "classification des données",
      "classifier",
      "niveau de classification",
      "données publiques",
      "données internes",
      "confidentiel",
      "restreint",
      "niveau de sensibilité",
      "catégorie de données",
      "données personnelles",
      "non personnel",
      "données sensibles",
    ],
  },
  sensitiveDataTopic: {
    en: [
      "sensitive data",
      "sensitive data protection",
      "pii",
      "personal data",
      "credentials",
      "secrets",
    ],
    fr: [
      "données sensibles",
      "protection des données sensibles",
      "données personnelles",
      "identifiants",
      "secrets",
    ],
  },
  encryptionAtRestSignals: {
    en: [
      "encrypt at rest",
      "encryption at rest",
      "field-level encryption",
      "column encryption",
      "database encryption",
      "aes",
    ],
    fr: [
      "chiffrement au repos",
      "chiffrement au niveau du champ",
      "chiffrement de colonne",
      "chiffrement de la base de données",
    ],
  },
  maskingSignals: {
    en: [
      "mask",
      "anonymiz",
      "pseudonymiz",
      "redact",
      "obfuscat",
      "tokeniz",
      "de-identif",
      "data scrub",
    ],
    fr: [
      "masquage",
      "masquer",
      "anonymis",
      "pseudonymis",
      "caviarder",
      "obfusqu",
      "tokenis",
      "dé-identifi",
      "nettoyage des données",
    ],
  },
  accessControlSignals: {
    en: [
      "row-level security",
      "rls",
      "column-level",
      "field-level access",
      "data access control",
      "need-to-know",
      "least privilege",
    ],
    fr: [
      "sécurité au niveau des lignes",
      "contrôle au niveau de la colonne",
      "accès au niveau du champ",
      "contrôle d'accès aux données",
      "besoin d'en connaître",
      "moindre privilège",
    ],
  },
  noSensitiveInLogsTopic: {
    en: [
      "sensitive data",
      "pii",
      "personal data",
      "log",
      "credentials",
      "tokens",
    ],
    fr: [
      "données sensibles",
      "données personnelles",
      "journal",
      "identifiants",
      "jetons",
    ],
  },
  noLogPIISignals: {
    en: [
      "no pii in log",
      "mask in log",
      "redact in log",
      "filter sensitive",
      "log sanitiz",
      "scrub log",
      "no sensitive data in log",
      "log masking",
      "exclude pii",
      "strip pii",
      "no personal data in log",
      "structured log",
      "safe logging",
    ],
    fr: [
      "aucune donnée personnelle dans les journaux",
      "masquer dans les journaux",
      "caviarder dans les journaux",
      "filtrer les données sensibles",
      "assainissement des journaux",
      "nettoyage des journaux",
      "aucune donnée sensible dans les journaux",
      "masquage des journaux",
      "exclure les données personnelles",
      "journalisation sécurisée",
    ],
  },
  dataMinimizationTopic: {
    en: [
      "data minimization",
      "personal data",
      "pii",
      "user data",
      "data collected",
    ],
    fr: [
      "minimisation des données",
      "données personnelles",
      "données utilisateur",
      "données collectées",
    ],
  },
  dataMinimizationSignals: {
    en: [
      "data minimization",
      "minimal data",
      "minimise",
      "collect only",
      "store only",
      "need-to-know",
      "purpose limitation",
      "data purpose",
      "justified",
      "necessary data",
      "required fields only",
      "no unnecessary",
      "reduce data footprint",
    ],
    fr: [
      "minimisation des données",
      "données minimales",
      "minimiser",
      "collecter uniquement",
      "stocker uniquement",
      "besoin d'en connaître",
      "limitation de la finalité",
      "finalité des données",
      "justifié",
      "données nécessaires",
      "champs requis uniquement",
      "réduire l'empreinte des données",
    ],
  },
  auditTrailTopic: {
    en: [
      "audit",
      "audit trail",
      "compliance",
      "authentication events",
      "data access",
    ],
    fr: [
      "audit",
      "piste d'audit",
      "conformité",
      "événements d'authentification",
      "accès aux données",
    ],
  },
  auditTrailSignals: {
    en: [
      "audit trail",
      "audit log",
      "audit event",
      "who did what",
      "who/what/when",
      "accountability",
      "compliance log",
      "activity log",
      "change log",
      "access log",
      "security log",
      "event sourcing",
      "tamper-proof log",
      "immutable log",
    ],
    fr: [
      "piste d'audit",
      "journal d'audit",
      "événement d'audit",
      "qui a fait quoi",
      "traçabilité",
      "journal de conformité",
      "journal d'activité",
      "journal des modifications",
      "journal d'accès",
      "journal de sécurité",
      "journal inviolable",
      "journal immuable",
    ],
  },
  consentErasureTopic: {
    en: [
      "consent",
      "erasure",
      "personal data",
      "gdpr",
      "privacy compliance",
      "user data",
    ],
    fr: [
      "consentement",
      "effacement",
      "données personnelles",
      "rgpd",
      "conformité vie privée",
      "données utilisateur",
    ],
  },
  consentSignals: {
    en: [
      "consent",
      "opt-in",
      "opt-out",
      "user agreement",
      "privacy preference",
      "data subject",
      "lawful basis",
    ],
    fr: ["consentement", "base légale", "personne concernée"],
  },
  erasureSignals: {
    en: [
      "right to erasure",
      "right to deletion",
      "right to be forgotten",
      "gdpr erasure",
      "data deletion",
      "cascade delete",
      "soft delete",
      "hard delete",
      "purge",
      "anonymize on delete",
      "account deletion",
      "data removal",
    ],
    fr: [
      "droit à l'effacement",
      "droit à l'oubli",
      "suppression des données",
      "suppression du compte",
    ],
  },
} as const satisfies Record<string, LexiconConcept>;
