import type { LexiconConcept } from "./lexicon-types.js";

/** Bilingual concept groups consumed by resilience-rules.ts. */
export const RESILIENCE_LEXICON = {
  errorHandlingTopic: {
    en: [
      "error",
      "exception",
      "error handling",
      "error propagation",
      "swallowed exception",
    ],
    fr: [
      "erreur",
      "exception",
      "gestion des erreurs",
      "propagation des erreurs",
      "exception avalée",
    ],
  },
  domainErrorSignals: {
    en: [
      "domain error",
      "error type",
      "error enum",
      "error class",
      "custom exception",
      "business exception",
      "typed error",
      "error hierarchy",
      "error code",
      "error catalog",
    ],
    fr: [
      "erreur de domaine",
      "type d'erreur",
      "énumération d'erreurs",
      "classe d'erreur",
      "exception personnalisée",
      "exception métier",
      "erreur typée",
      "hiérarchie d'erreurs",
      "code d'erreur",
      "catalogue d'erreurs",
    ],
  },
  propagationSignals: {
    en: [
      "error propagation",
      "error boundary",
      "error handling strategy",
      "catch and rethrow",
      "error translation",
      "error mapping",
      "exception filter",
      "global error handler",
      "error middleware",
      "no swallow",
      "never swallow",
      "always propagate",
    ],
    fr: [
      "propagation des erreurs",
      "stratégie de gestion des erreurs",
      "capturer et relancer",
      "traduction des erreurs",
      "gestionnaire d'erreurs global",
      "middleware d'erreurs",
      "ne jamais avaler",
      "toujours propager",
    ],
  },
  resiliencePatternsTopic: {
    en: [
      "resilience",
      "circuit breaker",
      "retry",
      "external dependency",
      "remote call",
      "transient",
    ],
    fr: [
      "résilience",
      "disjoncteur",
      "nouvelle tentative",
      "dépendance externe",
      "appel distant",
      "transitoire",
    ],
  },
  resiliencePatternsSignals: {
    en: [
      "circuit breaker",
      "retry",
      "exponential backoff",
      "timeout",
      "bulkhead",
      "rate limit",
      "failure isolation",
      "fault tolerance",
      "resilience",
      "health check",
      "dead letter",
      "fallback",
      "backpressure",
      "load shedding",
    ],
    fr: [
      "disjoncteur",
      "nouvelle tentative",
      "attente exponentielle",
      "délai d'expiration",
      "cloisonnement",
      "isolation des pannes",
      "tolérance aux pannes",
      "résilience",
      "vérification de santé",
      "file de lettres mortes",
      "repli",
      "contre-pression",
      "délestage de charge",
    ],
  },
  gracefulDegradationTopic: {
    en: [
      "graceful degradation",
      "degradation",
      "fallback",
      "dependency failure",
      "cascading failure",
    ],
    fr: [
      "dégradation gracieuse",
      "dégradation",
      "repli",
      "défaillance de dépendance",
      "défaillance en cascade",
    ],
  },
  gracefulDegradationSignals: {
    en: [
      "graceful degradation",
      "degrade gracefully",
      "fallback",
      "fail gracefully",
      "partial failure",
      "degraded mode",
      "offline mode",
      "cache fallback",
      "default response",
      "service unavailable",
      "cascading failure",
      "blast radius",
    ],
    fr: [
      "dégradation gracieuse",
      "se dégrader gracieusement",
      "repli",
      "échouer gracieusement",
      "défaillance partielle",
      "mode dégradé",
      "mode hors ligne",
      "repli sur cache",
      "réponse par défaut",
      "service indisponible",
      "défaillance en cascade",
    ],
  },
  transactionBoundariesTopic: {
    en: [
      "transaction",
      "rollback",
      "atomic",
      "multi-step",
      "read-only",
      "no writes",
      "database",
    ],
    fr: [
      "transaction",
      "annulation",
      "atomique",
      "plusieurs étapes",
      "lecture seule",
      "aucune écriture",
      "base de données",
    ],
  },
  transactionBoundariesSignals: {
    en: [
      "transaction",
      "transactional",
      "atomicity",
      "atomic operation",
      "isolation level",
      "rollback",
      "commit",
      "saga",
      "compensating transaction",
      "eventual consistency",
      "two-phase commit",
      "optimistic lock",
      "pessimistic lock",
      "idempoten",
      "exactly-once",
      "at-least-once",
    ],
    fr: [
      "transaction",
      "transactionnel",
      "atomicité",
      "opération atomique",
      "niveau d'isolation",
      "annulation",
      "validation",
      "transaction compensatoire",
      "cohérence à terme",
      "validation en deux phases",
      "verrou optimiste",
      "verrou pessimiste",
      "idempotent",
    ],
  },
  errorFormatTopic: {
    en: [
      "error format",
      "error response",
      "error envelope",
      "error code",
      "error catalog",
    ],
    fr: [
      "format d'erreur",
      "réponse d'erreur",
      "enveloppe d'erreur",
      "code d'erreur",
      "catalogue d'erreurs",
    ],
  },
  errorFormatSignals: {
    en: [
      "error format",
      "error response format",
      "error schema",
      "error contract",
      "rfc 7807",
      "problem detail",
      "error code",
      "error_code",
      "error response structure",
      "standardized error",
      "consistent error",
      "error envelope",
      "error body",
      "machine-readable error",
    ],
    fr: [
      "format d'erreur",
      "format de réponse d'erreur",
      "schéma d'erreur",
      "contrat d'erreur",
      "détail du problème",
      "code d'erreur",
      "structure de réponse d'erreur",
      "erreur standardisée",
      "erreur cohérente",
      "enveloppe d'erreur",
      "corps d'erreur",
      "erreur exploitable par une machine",
    ],
  },
} as const satisfies Record<string, LexiconConcept>;
